<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="48" started-at="2017-07-01T08:31:58Z" finished-at="2017-07-01T08:31:58Z">
    <groups>
      <group name="checkintest">
        <method signature="GroupTestExample.testPrintMessage()[pri:0, instance:test.GroupTestExample@58651fd0]" name="testPrintMessage" class="test.GroupTestExample"/>
      </group> <!-- checkintest -->
      <group name="functest">
        <method signature="GroupTestExample.testPrintMessage()[pri:0, instance:test.GroupTestExample@58651fd0]" name="testPrintMessage" class="test.GroupTestExample"/>
        <method signature="GroupTestExample.testingExitMessage()[pri:0, instance:test.GroupTestExample@58651fd0]" name="testingExitMessage" class="test.GroupTestExample"/>
      </group> <!-- functest -->
    </groups>
    <test name="test1" duration-ms="48" started-at="2017-07-01T08:31:58Z" finished-at="2017-07-01T08:31:58Z">
      <class name="test.GroupTestExample">
        <test-method status="PASS" signature="testPrintMessage()[pri:0, instance:test.GroupTestExample@58651fd0]" name="testPrintMessage" duration-ms="17" started-at="2017-07-01T16:31:58Z" finished-at="2017-07-01T16:31:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPrintMessage -->
        <test-method status="FAIL" signature="testingExitMessage()[pri:0, instance:test.GroupTestExample@58651fd0]" name="testingExitMessage" duration-ms="5" started-at="2017-07-01T16:31:58Z" finished-at="2017-07-01T16:31:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [www..com] but found [www.tutorialspoint.com]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [www..com] but found [www.tutorialspoint.com]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at test.GroupTestExample.testingExitMessage(GroupTestExample.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testingExitMessage -->
      </class> <!-- test.GroupTestExample -->
    </test> <!-- test1 -->
  </suite> <!-- Suite1 -->
</testng-results>
